version: "3.9"

services:
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pruebacbc
      POSTGRES_DB: cbc
      
  app:
    build: ./
    ports:
      - "3001:3001"
    volumes:
      - ./:/user/app
    env_file:
      - "./.env"
    depends_on:
      - db
    command: npm run start:prod